//simple c program 
/*
name:ANDLIANE KARANJA
REG:CT100/G/26193/25
Description:infomation technology units
*/

#include <stdio.h>

int main() {
 printf("SPH 2107 ANALOGUE ELECTRONICS\n");
 printf("ICU 2101 COMMUNICATION AND INFORMATION LITERACY SKILLS\n");
 printf("SPI 2102 COMPUTER SYSTEM AND ORGANIZATION\n");
 printf("SPI 2120 ESSENTIALS OF ACCOUNTING\n");
 printf("UCU 2105 FUNDAMENTALS OF ICT\n");
 printf("SPI 2103 INTRODUCTION TO COMPUTER APPLICATIONS\n");
 printf("SPI 2101 INTRODUCTION TO PROGRAMMING AND ALGORITHS\n");
 printf("SPM 2104 MATHEMATICS FOR SCIENCE\n");
 }